server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false

turbine:
  appConfig: MYSPRINGBOOTAPI
  instanceUrlSuffix: /hystrix.stream
  clusterNameExpression: new String("default")

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
