spring:
    application:
        name: myspringbootapi

eureka:
    instance:
      statusPageUrlPath: ${management.context-path}/info
      healthCheckUrlPath: ${management.context-path}/health
    client:
      healthcheck:
        enabled: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/