info:
  component: Zuul Server

spring:
    cloud:
      config:
        enabled: false
    application:
        name: my-zuul-router

ribbon:
  okToRetryOnAllErrors: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  restclient:
    enabled: true
  eureka:
    enabled: true

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080

zuul:
  routes:
    myspringbootapi:
      path: /myspringbootapi/**
      retryable: true




endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG

management:
  context-path: /manage
  port: 8081
