server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
